/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppArsipRouteImport } from './routes/_app/arsip'
import { Route as AppAsetRouteImport } from './routes/_app/aset'
import { Route as AppBumdesRouteImport } from './routes/_app/bumdes'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPengaturanRouteImport } from './routes/_app/pengaturan'
import { Route as AppProdukHukumRouteImport } from './routes/_app/produk-hukum'
import { Route as AppSpjRouteImport } from './routes/_app/spj'
import { Route as AppSuratRouteImport } from './routes/_app/surat'
import { Route as AppSpjIndexRouteImport } from './routes/_app/spj.index'
import { Route as AppSuratIndexRouteImport } from './routes/_app/surat.index'
import { Route as AppSuratIdRouteImport } from './routes/_app/surat.$id'
import { Route as AppSpjKegiatanIdRouteImport } from './routes/_app/spj.kegiatan.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppArsipRoute = AppArsipRouteImport.update({
  id: '/arsip',
  path: '/arsip',
  getParentRoute: () => AppRoute,
} as any)
const AppAsetRoute = AppAsetRouteImport.update({
  id: '/aset',
  path: '/aset',
  getParentRoute: () => AppRoute,
} as any)
const AppBumdesRoute = AppBumdesRouteImport.update({
  id: '/bumdes',
  path: '/bumdes',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPengaturanRoute = AppPengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => AppRoute,
} as any)
const AppProdukHukumRoute = AppProdukHukumRouteImport.update({
  id: '/produk-hukum',
  path: '/produk-hukum',
  getParentRoute: () => AppRoute,
} as any)
const AppSpjRoute = AppSpjRouteImport.update({
  id: '/spj',
  path: '/spj',
  getParentRoute: () => AppRoute,
} as any)
const AppSuratRoute = AppSuratRouteImport.update({
  id: '/surat',
  path: '/surat',
  getParentRoute: () => AppRoute,
} as any)
const AppSpjIndexRoute = AppSpjIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSpjRoute,
} as any)
const AppSuratIndexRoute = AppSuratIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSuratRoute,
} as any)
const AppSuratIdRoute = AppSuratIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSuratRoute,
} as any)
const AppSpjKegiatanIdRoute = AppSpjKegiatanIdRouteImport.update({
  id: '/kegiatan/$id',
  path: '/kegiatan/$id',
  getParentRoute: () => AppSpjRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/arsip': typeof AppArsipRoute
  '/aset': typeof AppAsetRoute
  '/bumdes': typeof AppBumdesRoute
  '/dashboard': typeof AppDashboardRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/produk-hukum': typeof AppProdukHukumRoute
  '/spj': typeof AppSpjRouteWithChildren
  '/surat': typeof AppSuratRouteWithChildren
  '/surat/$id': typeof AppSuratIdRoute
  '/spj/': typeof AppSpjIndexRoute
  '/surat/': typeof AppSuratIndexRoute
  '/spj/kegiatan/$id': typeof AppSpjKegiatanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/arsip': typeof AppArsipRoute
  '/aset': typeof AppAsetRoute
  '/bumdes': typeof AppBumdesRoute
  '/dashboard': typeof AppDashboardRoute
  '/pengaturan': typeof AppPengaturanRoute
  '/produk-hukum': typeof AppProdukHukumRoute
  '/surat/$id': typeof AppSuratIdRoute
  '/spj': typeof AppSpjIndexRoute
  '/surat': typeof AppSuratIndexRoute
  '/spj/kegiatan/$id': typeof AppSpjKegiatanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/arsip': typeof AppArsipRoute
  '/_app/aset': typeof AppAsetRoute
  '/_app/bumdes': typeof AppBumdesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/pengaturan': typeof AppPengaturanRoute
  '/_app/produk-hukum': typeof AppProdukHukumRoute
  '/_app/spj': typeof AppSpjRouteWithChildren
  '/_app/surat': typeof AppSuratRouteWithChildren
  '/_app/surat/$id': typeof AppSuratIdRoute
  '/_app/spj/': typeof AppSpjIndexRoute
  '/_app/surat/': typeof AppSuratIndexRoute
  '/_app/spj/kegiatan/$id': typeof AppSpjKegiatanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/arsip'
    | '/aset'
    | '/bumdes'
    | '/dashboard'
    | '/pengaturan'
    | '/produk-hukum'
    | '/spj'
    | '/surat'
    | '/surat/$id'
    | '/spj/'
    | '/surat/'
    | '/spj/kegiatan/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/arsip'
    | '/aset'
    | '/bumdes'
    | '/dashboard'
    | '/pengaturan'
    | '/produk-hukum'
    | '/surat/$id'
    | '/spj'
    | '/surat'
    | '/spj/kegiatan/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/arsip'
    | '/_app/aset'
    | '/_app/bumdes'
    | '/_app/dashboard'
    | '/_app/pengaturan'
    | '/_app/produk-hukum'
    | '/_app/spj'
    | '/_app/surat'
    | '/_app/surat/$id'
    | '/_app/spj/'
    | '/_app/surat/'
    | '/_app/spj/kegiatan/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/arsip': {
      id: '/_app/arsip'
      path: '/arsip'
      fullPath: '/arsip'
      preLoaderRoute: typeof AppArsipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/aset': {
      id: '/_app/aset'
      path: '/aset'
      fullPath: '/aset'
      preLoaderRoute: typeof AppAsetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bumdes': {
      id: '/_app/bumdes'
      path: '/bumdes'
      fullPath: '/bumdes'
      preLoaderRoute: typeof AppBumdesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pengaturan': {
      id: '/_app/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof AppPengaturanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/produk-hukum': {
      id: '/_app/produk-hukum'
      path: '/produk-hukum'
      fullPath: '/produk-hukum'
      preLoaderRoute: typeof AppProdukHukumRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spj': {
      id: '/_app/spj'
      path: '/spj'
      fullPath: '/spj'
      preLoaderRoute: typeof AppSpjRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surat': {
      id: '/_app/surat'
      path: '/surat'
      fullPath: '/surat'
      preLoaderRoute: typeof AppSuratRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/spj/': {
      id: '/_app/spj/'
      path: '/'
      fullPath: '/spj/'
      preLoaderRoute: typeof AppSpjIndexRouteImport
      parentRoute: typeof AppSpjRoute
    }
    '/_app/surat/': {
      id: '/_app/surat/'
      path: '/'
      fullPath: '/surat/'
      preLoaderRoute: typeof AppSuratIndexRouteImport
      parentRoute: typeof AppSuratRoute
    }
    '/_app/surat/$id': {
      id: '/_app/surat/$id'
      path: '/$id'
      fullPath: '/surat/$id'
      preLoaderRoute: typeof AppSuratIdRouteImport
      parentRoute: typeof AppSuratRoute
    }
    '/_app/spj/kegiatan/$id': {
      id: '/_app/spj/kegiatan/$id'
      path: '/kegiatan/$id'
      fullPath: '/spj/kegiatan/$id'
      preLoaderRoute: typeof AppSpjKegiatanIdRouteImport
      parentRoute: typeof AppSpjRoute
    }
  }
}

interface AppSpjRouteChildren {
  AppSpjIndexRoute: typeof AppSpjIndexRoute
  AppSpjKegiatanIdRoute: typeof AppSpjKegiatanIdRoute
}

const AppSpjRouteChildren: AppSpjRouteChildren = {
  AppSpjIndexRoute: AppSpjIndexRoute,
  AppSpjKegiatanIdRoute: AppSpjKegiatanIdRoute,
}

const AppSpjRouteWithChildren =
  AppSpjRoute._addFileChildren(AppSpjRouteChildren)

interface AppSuratRouteChildren {
  AppSuratIdRoute: typeof AppSuratIdRoute
  AppSuratIndexRoute: typeof AppSuratIndexRoute
}

const AppSuratRouteChildren: AppSuratRouteChildren = {
  AppSuratIdRoute: AppSuratIdRoute,
  AppSuratIndexRoute: AppSuratIndexRoute,
}

const AppSuratRouteWithChildren = AppSuratRoute._addFileChildren(
  AppSuratRouteChildren,
)

interface AppRouteChildren {
  AppArsipRoute: typeof AppArsipRoute
  AppAsetRoute: typeof AppAsetRoute
  AppBumdesRoute: typeof AppBumdesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppPengaturanRoute: typeof AppPengaturanRoute
  AppProdukHukumRoute: typeof AppProdukHukumRoute
  AppSpjRoute: typeof AppSpjRouteWithChildren
  AppSuratRoute: typeof AppSuratRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppArsipRoute: AppArsipRoute,
  AppAsetRoute: AppAsetRoute,
  AppBumdesRoute: AppBumdesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppPengaturanRoute: AppPengaturanRoute,
  AppProdukHukumRoute: AppProdukHukumRoute,
  AppSpjRoute: AppSpjRouteWithChildren,
  AppSuratRoute: AppSuratRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
